b'--- utils.py\t(original)'
b'+++ utils.py\t(refactored)'
b'@@ -11,8 +11,9 @@'
b' # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.'
b' # See the License for the specific language governing permissions and'
b' # limitations under the License.'
b'-"""Utility functions to display the pose detection results."""'
b'+u"""Utility functions to display the pose detection results."""'
b' '
b'+from __future__ import absolute_import'
b' from typing import List'
b' '
b' import cv2'
b'@@ -27,10 +28,10 @@'
b' '
b' '
b' def visualize('
b'-    image: np.ndarray,'
b'-    detections: List[Detection],'
b'-) -> np.ndarray:'
b'-  """Draws bounding boxes on the input image and return it.'
b'+    image,'
b'+    detections,'
b'+):'
b'+  u"""Draws bounding boxes on the input image and return it.'
b' '
b'   Args:'
b'     image: The input RGB image.'
b'@@ -49,7 +50,7 @@'
b'     category = detection.categories[0]'
b'     class_name = category.label'
b'     probability = round(category.score, 2)'
b"-    result_text = class_name + ' (' + str(probability) + ')'"
b"+    result_text = class_name + u' (' + unicode(probability) + u')'"
b'     text_location = (_MARGIN + detection.bounding_box.left,'
b'                      _MARGIN + _ROW_SIZE + detection.bounding_box.top)'
b'     cv2.putText(image, result_text, text_location, cv2.FONT_HERSHEY_PLAIN,'
